export const accountOnboarding = [
  'email',
  'firstname',
  'lastname',
  'gender',
  'status',
  'status/company-name',
  'status/siret',
  'status/tva',
  'birthdate',
  'country',
  'zipcode',
  'city',
  'street',
  'phonenumber',
  'password',
  'passwordconfirmation',
  'emailoptin',
  'validation',
  'confirmation'
]

export const productOnboarding = [
  'announcement-title',
  'media-upload',
  // 'product-consumable',
  'product-category',
  'product-brand',
  // 'product-type',
  // 'product-reference',
  'product-state',
  'product-description',
  'product-zipcode',
  // 'product-delivery',
  'product-weight',
  'is-warrantied',
  'warranty-duration',
  'video-upload',
  'reserve-price',
  'announce-overview'
]
